<div class="container-fluid">
    <div class="container">
        <h1> home page</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="container">
        <h3> paragraphe 1</h3>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias obcaecati assumenda, facere tenetur ex odio saepe et blanditiis omnis voluptate ullam libero praesentium dolores aspernatur natus unde ducimus corrupti distinctio optio labore consequuntur sint. Culpa nihil neque modi, temporibus ipsam magnam accusantium beatae placeat, cumque expedita dolor minus debitis eum aliquid dolorem quo molestias maxime labore alias impedit dignissimos. At modi perferendis corrupti non unde quae ipsa suscipit repellendus sapiente! Dolor harum, rem dolorem iste eos accusantium totam quas deserunt praesentium ullam porro hic libero reiciendis excepturi, veritatis error autem! Velit minus consectetur odio ab ipsam provident illum, ex, animi voluptates, assumenda itaque voluptatem. Deserunt accusamus aperiam, fuga eveniet eligendi itaque possimus impedit reprehenderit harum, sit dignissimos architecto laboriosam. Ea minima dolores debitis. Provident minima aliquam accusantium voluptatum nemo labore atque laborum quo iusto perspiciatis assumenda at repellat quae sit doloribus impedit, ipsa quia quam ab, asperiores adipisci illo facilis velit! Itaque aperiam tempore officia sequi cupiditate ad architecto nisi laboriosam provident, minus natus placeat soluta rerum fuga dicta veritatis ipsum nobis dignissimos, earum enim alias! Doloremque voluptates cupiditate dolorum commodi aspernatur? Explicabo error animi dolor sunt, officia aspernatur alias? Rerum sunt similique libero, temporibus nostrum doloribus! Quidem, non suscipit.</p>
        <label for="name"> pour boir plus cliquez </label>
        <input id="name" type="submit" value="ICI" href="/posts/:id">
    </div>
    <div class="container">
        <h3> paragraphe 2</h3>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias obcaecati assumenda, facere tenetur ex odio saepe et blanditiis omnis voluptate ullam libero praesentium dolores aspernatur natus unde ducimus corrupti distinctio optio labore consequuntur sint. Culpa nihil neque modi, temporibus ipsam magnam accusantium beatae placeat, cumque expedita dolor minus debitis eum aliquid dolorem quo molestias maxime labore alias impedit dignissimos. At modi perferendis corrupti non unde quae ipsa suscipit repellendus sapiente! Dolor harum, rem dolorem iste eos accusantium totam quas deserunt praesentium ullam porro hic libero reiciendis excepturi, veritatis error autem! Velit minus consectetur odio ab ipsam provident illum, ex, animi voluptates, assumenda itaque voluptatem. Deserunt accusamus aperiam, fuga eveniet eligendi itaque possimus impedit reprehenderit harum, sit dignissimos architecto laboriosam. Ea minima dolores debitis. Provident minima aliquam accusantium voluptatum nemo labore atque laborum quo iusto perspiciatis assumenda at repellat quae sit doloribus impedit, ipsa quia quam ab, asperiores adipisci illo facilis velit! Itaque aperiam tempore officia sequi cupiditate ad architecto nisi laboriosam provident, minus natus placeat soluta rerum fuga dicta veritatis ipsum nobis dignissimos, earum enim alias! Doloremque voluptates cupiditate dolorum commodi aspernatur? Explicabo error animi dolor sunt, officia aspernatur alias? Rerum sunt similique libero, temporibus nostrum doloribus! Quidem, non suscipit.</p>
    </div>
    <div class="container">
        <h3> paragraphe 3</h3>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias obcaecati assumenda, facere tenetur ex odio saepe et blanditiis omnis voluptate ullam libero praesentium dolores aspernatur natus unde ducimus corrupti distinctio optio labore consequuntur sint. Culpa nihil neque modi, temporibus ipsam magnam accusantium beatae placeat, cumque expedita dolor minus debitis eum aliquid dolorem quo molestias maxime labore alias impedit dignissimos. At modi perferendis corrupti non unde quae ipsa suscipit repellendus sapiente! Dolor harum, rem dolorem iste eos accusantium totam quas deserunt praesentium ullam porro hic libero reiciendis excepturi, veritatis error autem! Velit minus consectetur odio ab ipsam provident illum, ex, animi voluptates, assumenda itaque voluptatem. Deserunt accusamus aperiam, fuga eveniet eligendi itaque possimus impedit reprehenderit harum, sit dignissimos architecto laboriosam. Ea minima dolores debitis. Provident minima aliquam accusantium voluptatum nemo labore atque laborum quo iusto perspiciatis assumenda at repellat quae sit doloribus impedit, ipsa quia quam ab, asperiores adipisci illo facilis velit! Itaque aperiam tempore officia sequi cupiditate ad architecto nisi laboriosam provident, minus natus placeat soluta rerum fuga dicta veritatis ipsum nobis dignissimos, earum enim alias! Doloremque voluptates cupiditate dolorum commodi aspernatur? Explicabo error animi dolor sunt, officia aspernatur alias? Rerum sunt similique libero, temporibus nostrum doloribus! Quidem, non suscipit.</p>
    </div>
    <div class="container">
        <h3> paragraphe 4</h3>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias obcaecati assumenda, facere tenetur ex odio saepe et blanditiis omnis voluptate ullam libero praesentium dolores aspernatur natus unde ducimus corrupti distinctio optio labore consequuntur sint. Culpa nihil neque modi, temporibus ipsam magnam accusantium beatae placeat, cumque expedita dolor minus debitis eum aliquid dolorem quo molestias maxime labore alias impedit dignissimos. At modi perferendis corrupti non unde quae ipsa suscipit repellendus sapiente! Dolor harum, rem dolorem iste eos accusantium totam quas deserunt praesentium ullam porro hic libero reiciendis excepturi, veritatis error autem! Velit minus consectetur odio ab ipsam provident illum, ex, animi voluptates, assumenda itaque voluptatem. Deserunt accusamus aperiam, fuga eveniet eligendi itaque possimus impedit reprehenderit harum, sit dignissimos architecto laboriosam. Ea minima dolores debitis. Provident minima aliquam accusantium voluptatum nemo labore atque laborum quo iusto perspiciatis assumenda at repellat quae sit doloribus impedit, ipsa quia quam ab, asperiores adipisci illo facilis velit! Itaque aperiam tempore officia sequi cupiditate ad architecto nisi laboriosam provident, minus natus placeat soluta rerum fuga dicta veritatis ipsum nobis dignissimos, earum enim alias! Doloremque voluptates cupiditate dolorum commodi aspernatur? Explicabo error animi dolor sunt, officia aspernatur alias? Rerum sunt similique libero, temporibus nostrum doloribus! Quidem, non suscipit.</p>
    </div>
    <div class="container">
        <h3> paragraphe 5</h3>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias obcaecati assumenda, facere tenetur ex odio saepe et blanditiis omnis voluptate ullam libero praesentium dolores aspernatur natus unde ducimus corrupti distinctio optio labore consequuntur sint. Culpa nihil neque modi, temporibus ipsam magnam accusantium beatae placeat, cumque expedita dolor minus debitis eum aliquid dolorem quo molestias maxime labore alias impedit dignissimos. At modi perferendis corrupti non unde quae ipsa suscipit repellendus sapiente! Dolor harum, rem dolorem iste eos accusantium totam quas deserunt praesentium ullam porro hic libero reiciendis excepturi, veritatis error autem! Velit minus consectetur odio ab ipsam provident illum, ex, animi voluptates, assumenda itaque voluptatem. Deserunt accusamus aperiam, fuga eveniet eligendi itaque possimus impedit reprehenderit harum, sit dignissimos architecto laboriosam. Ea minima dolores debitis. Provident minima aliquam accusantium voluptatum nemo labore atque laborum quo iusto perspiciatis assumenda at repellat quae sit doloribus impedit, ipsa quia quam ab, asperiores adipisci illo facilis velit! Itaque aperiam tempore officia sequi cupiditate ad architecto nisi laboriosam provident, minus natus placeat soluta rerum fuga dicta veritatis ipsum nobis dignissimos, earum enim alias! Doloremque voluptates cupiditate dolorum commodi aspernatur? Explicabo error animi dolor sunt, officia aspernatur alias? Rerum sunt similique libero, temporibus nostrum doloribus! Quidem, non suscipit.</p>
    </div>
</div>